@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.acessToken}}

@carUuid = {{createCarOwned.response.body.id}}

@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Gustavo
@userEmailForTesting = user2@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "{{userNameForTesting}} Otávio",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "{{userPasswordForTesting}}",
  "newPassword": "{{userNewPasswordForTesting}}"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

# POST ########################################################################

### Create car owned
# @name createCarOwned
POST {{baseUrl}}/car/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "fipeCode": "123456",
    "brand": "Volks",
    "model": "golf",
    "version": "tsi",
    "year": 2018,
    "plate": "ABC1D23",
    "fuel": "Gasolina",
    "price": 45000.50,
    "mileage": 75000,
    "color": "Prata",
    "description": "Carro bem cuidado, com todas as revisões em dia.",
    "images": [
        "https://via.placeholder.com/400",
        "https://via.placeholder.com/401"
        ],
    "active": true
}

### Read all car public
# @name readAllCarPublic
GET {{baseUrl}}/car/

### Read one car public
# @name readOneCarPublic
GET {{baseUrl}}/car/{{carUuid}}

### Read all car owned
# @name readAllCarOwned
GET {{baseUrl}}/car/me
Authorization: Bearer {{jwtToken}}

### Read one car owned
# @name readOneCarOwned
GET {{baseUrl}}/car/me/{{carUuid}}
Authorization: Bearer {{jwtToken}}

### Update one car owned
# @name updateOneCarOwned
PATCH {{baseUrl}}/car/me/{{carUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "brand": "Honda",
    "model": "Civic",
    "version": "exs",
    "description": "Carro bem cuidado, com todas as revisões em dia. 1",
    "active": true
}

### Delete one car owned
# @name deleteOneCarOwned
DELETE {{baseUrl}}/car/me/{{carUuid}}
Authorization: Bearer {{jwtToken}}

# UPLOAD ######################################################################

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.jpeg"
Content-Type: image/jpeg

< ../dev/images/image.jpeg
------BryenFormBoundary--

### Read Image
# @name readImage
GET {{imageUrl}}

###############################################################################